### ISSUE TITLE
Error when using theme variables

### ISSUE THREAD

**Issue by malviyaritesh** [nmn/sveltekit-stylex#1]
I'm playing with StyleX to use in my SvelteKit projects and I think StyleX is great.
Thanks for the awesome open source work.

Your provided example doesn't show how to use [theme variables ](https://stylexjs.com/docs/learn/theming/defining-variables/#defining-variables-1). I tried, but I'm getting following error:

```
src/styles/globalTokens.stylex.ts.ts: No filename found for generating theme name.
2:03:11 AM [vite] Error when evaluating SSR module /src/routes/+page.svelte: failed to import "/src/styles/globalTokens.stylex.ts"
```

[Here](https://codesandbox.io/p/devbox/stylex-demo-glxfwf?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqa8qbj300063b5wjk4yiyll%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqa8qbj300023b5wrkrdv5q2%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqa8qbj300043b5wxaodw3qp%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqa8qbj300053b5wp26bxhgp%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqa8qbj300023b5wrkrdv5q2%2522%253A%257B%2522id%2522%253A%2522clqa8qbj300023b5wrkrdv5q2%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clqa8qbj300053b5wp26bxhgp%2522%253A%257B%2522id%2522%253A%2522clqa8qbj300053b5wp26bxhgp%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clqa8qvf4008g3b5wfmpqxjox%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqa8qvf4008g3b5wfmpqxjox%2522%257D%252C%2522clqa8qbj300043b5wxaodw3qp%2522%253A%257B%2522id%2522%253A%2522clqa8qbj300043b5wxaodw3qp%2522%252C%2522activeTabId%2522%253A%2522clqa9gppq01of3b5ww57imn2g%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqa8qbj300033b5wjidq6fll%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clqa8qbto0003efjc9i9385kx%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clqa9gppq01of3b5ww57imn2g%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) is a codesandbox, for what I've tried.

I'm not sure how to fix this. Can you please provide complete example similar to [next.js](https://github.com/facebook/stylex/tree/main/apps/nextjs-example)?

**Comment by nmn** [comment]
There is some discussion happening with the author of `vite-plugin-stylex` about the right approach for the Vite plugin which is why I haven't made much progress on this repo.

In the meantime, I'll try to unblock you.

**Comment by nmn** [comment]
Follow up: It was stupid bug in the Vite plugin. I've fixed it and tested that it works.

**Comment by nmn** [comment]
Scratch that. There's a bug in the production builds where the stylex variables are not included in the generated CSS file.

**Comment by nmn** [comment]
Fixed. Please see the vite plugin. The current implementation works for projects where all styles are StyleX. There are comments in the `generateBundle` function to change this behaviour.

**Comment by malviyaritesh** [comment]
Thanks for instant reply and solution.

I've updated the [codesandbox](https://codesandbox.io/p/devbox/stylex-demo-glxfwf?file=%2Fsrc%2Fstyles%2FglobalTokens.stylex.ts%3A2%2C1) and tried slightly complex rules. But the styles are not working.

**Comment by nmn** [comment]
I tried your code locally and while it's broken in dev mode, it worked when I used `npm run build && npm run preview`.

I believe there is an issue with the dev server/HMR in sveltekit.

Please see if the `vite-plugin-stylex` plugin works more reliably.

**Comment by malviyaritesh** [comment]
I tried [vite-plugin-stylex](https://www.npmjs.com/package/vite-plugin-stylex) too, but it is also throwing an error:

```
Error: stylex.defineVars should never be called. It should be compiled away.
```
I think, Stylex is not yet ready to be used with SvelteKit. I'll continue using my old styling solutions while waiting for Stylex to be ready.
